### ISSUE TITLE
Fail to find minimum

### ISSUE THREAD

**Issue by JennaVergeynst** [baktoft/yaps#2]
Hi @baktoft,

I'm trying out your YAPS R-package. I have new data now with a smaller and more regular burst interval (theoretically about 1 second), so this should be great to feed to YAPS :-)
However, I'm getting:
`Newton failed to find minimum.
In addition: Warning message:
In stats::nlminb(inp$inits, obj$fn, obj$gr) : NA/NaN function evaluation
outer mgc:  NaN 
Error in `[.default`(summary(jointrep), , 2) : 
  incorrect number of dimensions`

Does the warning message give you a clue about what's going wrong?

Below the code I'm using and attached a TOA file.

```
library(yaps)
set.seed(42)

pingType <- 'sbi'

toa_data <- read.csv(paste0(PATH, 'YAPS/TOA_data/TOA_46902.csv'), check.names = FALSE) # check.names False avoids that R puts X before receiver name
receivers <- colnames(toa_data)[3:(ncol(toa_data)-2)]
passings <- unique(toa_data$groups_pas)

hydro_data <- read.csv(paste0(PATH,'data/stations.csv'), row.names = 'Serial')
hydros <- hydro_data[rownames(hydro_data) %in% receivers,colnames(hydro_data) %in% c('X','Y')]
names(hydros) <- c("hx", "hy")


i=1
toa <- toa_data[toa_data$groups_pas ==passings[i],colnames(toa_data)%in% receivers]
toa <- t(as.matrix(toa))
T0 <- min(toa, na.rm=TRUE) #reshape so first TOA is 0
toa <- toa - T0

if(pingType == 'sbi'){
	inp <- getInp(hydros, toa, E_dist="Mixture", n_ss=10, pingType=pingType, sdInits=0)
} else if(pingType == 'rbi'){
	inp <- getInp(hydros, toa, E_dist="Mixture", n_ss=10, pingType=pingType, sdInits=0, rbi_min=rbi_min, rbi_max=rbi_max)
}
str(inp)

pl <- c()
maxIter <- ifelse(pingType=="sbi", 500, 5000)
outTmb <- runTmb(inp, maxIter=maxIter, getPlsd=TRUE, getRep=TRUE)

```

[TOA_46902.txt](https://github.com/baktoft/yaps/files/2783475/TOA_46902.txt)

**Comment by baktoft** [comment]
Hi @JennaVergeynst,
Thank you for your continued interest in YAPS :-).
Could you send me the file with station positions as well? Then, I will try to have a look and get it running.
Cheers, \hb

**Comment by JennaVergeynst** [comment]
Attached! Thank you!Yes, YAPS is our only hope on nice tracks ;-)
——Jenna VergeynstPhD ResearcherBIOMATH - Model-based analysis and optimisation of bioprocessesDepartment of Data Analysis and Mathematical ModellingFaculty of Bioscience EngineeringGhent UniversityCoupure Links 653, 9000 Gent, Belgiumtel +32 491 31 58 02

On 22 Jan 2019, at 20:52, Henrik Baktoft <notifications@github.com> wrote:Hi @JennaVergeynst,
Thank you for your continued interest in YAPS :-).
Could you send me the file with station positions as well? Then, I will try to have a look and get it running.
Cheers, \hb—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/baktoft/yaps","title":"baktoft/yaps","subtitle":"GitHub repository","main_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/header.png" class="">https://github.githubassets.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/avatar.png" class="">https://github.githubassets.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/baktoft/yaps" class="">https://github.com/baktoft/yaps</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@baktoft in #2: Hi @JennaVergeynst,\r\nThank you for your continued interest in YAPS :-).\r\nCould you send me the file with station positions as well? Then, I will try to have a look and get it running.\r\nCheers, \\hb"}],"action":{"name":"View Issue","url":"<a href="https://github.com/baktoft/yaps/issues/2#issuecomment-456538978" class="">https://github.com/baktoft/yaps/issues/2#issuecomment-456538978</a>"}}}
[
{
"@context": "<a href="http://schema.org" class="">http://schema.org</a>",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "<a href="https://github.com/baktoft/yaps/issues/2#issuecomment-456538978" class="">https://github.com/baktoft/yaps/issues/2#issuecomment-456538978</a>",
"url": "<a href="https://github.com/baktoft/yaps/issues/2#issuecomment-456538978" class="">https://github.com/baktoft/yaps/issues/2#issuecomment-456538978</a>",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "<a href="https://github.com" class="">https://github.com</a>"
}
}
]

**Comment by baktoft** [comment]
Hi Jenna, I don't see the station position file?

**Comment by JennaVergeynst** [comment]
Try again...


Serial,StationName,Start,End,Latitude,Longitude,Depth,X,Y,Z,ID

1284693,Ref1,2018-03-20T00:00:00Z,2018-08-22T00:00:00Z,47.81866569,10.22484318,0.5,1011.920124,973.1700789,-0.5,65001

1284694,Ref2,2018-03-20T00:00:00Z,2018-08-22T00:00:00Z,47.81877045,10.22478341,0.5,1007.444387,984.8174442,-0.5,65002

1284695,Ref3,2018-03-20T00:00:00Z,2018-08-22T00:00:00Z,47.81899478,10.22431413,0.5,972.3022504,1009.759618,-0.5,65003

1293347,Ref4,2018-04-19T00:00:00Z,2018-08-22T00:00:00Z,47.81971,10.22357,0.5,916.5781208,1089.283607,-0.5,65004

1293348,Ref5,2018-04-19T13:30:00Z,2018-08-22T00:00:00Z,47.81836717,10.22701148,0.5,1174.297751,939.9801529,-0.5,65005

1293349_1,Ref6,2018-04-19T11:00:00Z,2018-05-10T07:33:00Z,47.81789365,10.22642517,0.5,1130.392332,887.3306169,-0.5,65006

1293349_2,Ref6,2018-05-10T07:35:00Z,2018-08-22T00:00:00Z,47.81790022,10.22642378,0.5,1130.288081,888.0611005,-0.5,65006

461213,StA,2018-03-20T10:26:59.133Z,2018-08-23T00:00:00Z,47.81814375,10.22616453,0.5,1110.872595,915.1382324,-0.5,62213

461076_1,StB,2018-03-20T11:04:42.782Z,2018-03-22T11:06:51Z,47.81846535,10.22656976,0.5,1141.218184,950.896622,-0.5,62076

461076_2,StB,2018-03-22T13:54:29Z,2018-08-23T00:00:00Z,47.81849325,10.22668033,0.5,1149.498877,953.9983626,-0.5,62076

461135,StC,2018-03-20T10:55:24.438Z,2018-08-23T00:00:00Z,47.81856326,10.22613938,0.5,1108.988841,961.7817066,-0.5,62135

461140,StD,2018-03-20T11:14:01.126Z,2018-08-23T00:00:00Z,47.8183116,10.22571938,0.5,1077.536574,933.7996418,-0.5,62140

461206,StE,2018-03-20T11:45:00Z,2018-08-23T00:00:00Z,47.81863,10.22514512,0.5,1034.532054,969.2012186,-0.5,62206

461208_1,StF,2018-03-20T12:33:17.762Z,2018-04-29T14:39:00Z,47.81871308,10.2251807,0.5,1037.196274,978.4386227,-0.5,62208

461208_2,StF,2018-04-29T14:40:00Z,2018-06-13T14:47:30Z,47.8186941,10.22523511,0.5,1041.270837,976.3281142,-0.5,62208

461208_3,StF,2018-06-14T03:26:30Z,2018-08-23T00:00:00Z,47.81869901,10.22522576,0.5,1040.5706,976.8742554,-0.5,62208

461212_1,StG,2018-03-20T12:12:08.334Z,2018-04-29T14:39:00Z,47.8187393,10.22532325,0.5,1047.871434,981.354577,-0.5,62212

461212_2,StG,2018-04-29T14:40:00Z,2018-06-13T14:47:30Z,47.81873853,10.2253625,0.5,1050.810279,981.2682899,-0.5,62212

461212_3,StG,2018-06-14T03:26:30Z,2018-08-23T00:00:00Z,47.81874295,10.22535608,0.5,1050.329903,981.7597131,-0.5,62212

461211,StH,2018-03-20T12:39:34.213Z,2018-08-23T00:00:00Z,47.81897543,10.22479683,0.5,1008.449626,1007.608747,-0.5,62211

461059,StI,2018-03-20T12:52:27.582Z,2018-08-23T00:00:00Z,47.81893132,10.22468519,0.5,1000.088973,1002.703727,-0.5,62059

461075_1,StJ,2018-03-20T13:47:00Z,2018-04-29T14:39:15Z,47.81871809,10.22482364,0.5,1010.457018,978.9952536,-0.5,62075

461075_2,StJ,2018-04-29T14:40:29Z,2018-08-23T00:00:00Z,47.81871859,10.22482247,0.5,1010.369796,979.0511487,-0.5,62075

461207,StK,2018-03-20T13:41:00Z,2018-08-23T00:00:00Z,47.81885826,10.2243022,0.5,971.4081779,994.5812688,-0.5,62207

461209,StL,2018-03-22T10:41:52Z,2018-08-23T00:00:00Z,47.81909156,10.22450655,0.5,986.7118603,1020.520339,-0.5,62209

461210_1,StM,2018-03-20T13:52:00Z,2018-04-08T12:49:30Z,47.81931427,10.22410191,0.5,956.4095521,1045.283736,-0.5,62210

461210_2,StM,2018-04-08T12:51:59Z,2018-08-23T00:00:00Z,47.81931233,10.22411062,0.5,957.0624815,1045.067205,-0.5,62210

461214,StN,2018-03-20T14:24:43.414Z,2018-08-23T00:00:00Z,47.81912049,10.22376322,0.5,931.0468112,1023.7375,-0.5,62214

461215,StO,2018-03-20T14:02:00Z,2018-08-23T00:00:00Z,47.81929034,10.2234798,0.5,909.8225972,1042.623568,-0.5,62215

461218,StR,2018-03-21T11:08:16.581Z,2018-08-23T00:00:00Z,47.81954787,10.22373946,0.5,929.2678809,1071.257255,-0.5,62000

**Comment by baktoft** [comment]
Hi again,
I had a look at your data and found two major problems. 
1. order of hydros different between hydros and toa - they should be in the same order
2. the TOA matrix had some issues regarding structure - see comments in script below... I attempted a quick and dirty fix for this which made the model run, but the result seems a bit off - probably due to the fix being to quick and dirty. Try to make a better TOA-matrix and see if that helps...

This script should run and produce a track of sorts...

```R
library(yaps)
set.seed(42)

pingType <- 'sbi'

toa_data <- read.csv('TOA_46902.txt', check.names = FALSE) # check.names False avoids that R puts X before receiver name
receivers <- colnames(toa_data)[3:(ncol(toa_data)-2)]
passings <- unique(toa_data$groups_pas)

hydro_data <- read.csv('stations.csv', row.names = 'Serial')
hydros <- hydro_data[rownames(hydro_data) %in% receivers,colnames(hydro_data) %in% c('X','Y')]
names(hydros) <- c("hx", "hy")
plot(hydros)

# Check that order of hydros are the same as order in toa
rownames(hydros) == rownames(toa)
# Fix this...
hydros <- hydros[order(rownames(hydros)),]
# Better...
rownames(hydros) == rownames(toa)

# Make the grid centred close to 0;0
hydros[,'hx'] <- hydros[,'hx'] - 900
hydros[,'hy'] <- hydros[,'hy'] - 900

i=1
toa <- toa_data[toa_data$groups_pas ==passings[i],colnames(toa_data)%in% receivers]
toa <- t(as.matrix(toa))
T0 <- min(toa, na.rm=TRUE) #reshape so first TOA is 0
toa <- toa - T0


# TOA matrix needs to be very regular - i.e. one ping per column - this means include empty columns if a ping is not detected at all
# Check that TOA is well formatted
plot(diff(colMeans(toa, na.rm=TRUE))) # Doesn't look good - all points should be centred at the burst interval 1.25

# E.g. this section is not good - the ping at ~114 sec is found in three different columns
which(diff(colMeans(toa, na.rm=TRUE)) < 0.1)
toa[,90:95] 

# This section have a gap of ~5 seconds between columns 653 and 654
which(diff(colMeans(toa, na.rm=TRUE)) > 4)
toa[,650:655] 

# Below is a quick and dirty attempt to correct this TOA based on the data given...
# This should of course be done in a better way and sooner in the process, but just to try it out...
library(data.table)
rownames(toa) <- c()
long <- data.table(reshape2::melt(toa)[,c(1,3)])
colnames(long) <- c('h','toa')
long <- long[!is.na(toa), ]
head(long)

nping <- floor(max(long[,2]) / 1.25)
approx_toa <- 1:nping * 1.25

long_new <- data.table(expand.grid(1:16, approx_toa))
colnames(long_new) <- c('h','toa')

long[,roll:=toa]
long_new[,roll:=toa]

setkey(long, h, roll)
setkey(long_new, h, roll)

long_joined <- long[long_new, roll='nearest']
long_joined[which(abs(long_joined[,toa] - long_joined[,roll]) > 0.5)]$toa <- NA
long_joined <- long_joined[,c('h','toa','roll')]

new_toa <- reshape2::acast(long_joined, roll~h, value.var="toa")
rownames(new_toa) <- c()
new_toa <- t(new_toa)

# This is looking a bit better now, but not perfect...
plot(diff(colMeans(new_toa, na.rm=TRUE)))

inp <- getInp(hydros, new_toa, E_dist="Mixture", n_ss=10, pingType=pingType, sdInits=0)
str(inp)

pl <- c()
maxIter <- ifelse(pingType=="sbi", 500, 5000)
outTmb <- runTmb(inp, maxIter=maxIter, getPlsd=TRUE, getRep=TRUE)


str(outTmb)

# Estimates in pl
pl <- outTmb$pl

# Error estimates in plsd
plsd <- outTmb$plsd

# plot the resulting estimated track
# It doesn't look quite right, but the way to correct TOA above is really not the right way to do it ;-)
plot(hy~hx, data=hydros, type="p", asp=1, xlim=c(-100,300))
lines(pl$X~pl$Y, col="red")
```

Let me know how it turns out :-)
\hb

**Comment by JennaVergeynst** [comment]
Hi Henrik,

Thanks for these ideas!
I realised that the ping interval is actually not fixed, but random between 1.1 and 1.3 seconds, so  I should change the pingtype to 'rbi' I suppose.
Also there was another ping interval of 50 to 70 seconds present, of another kind of pings, which I could throw out, but probably this also altered the quality of the track...

So for the random ping interval, is it also needed to have the TOA matrix filled in where there are gaps? So for instance fill it with NaN rows on every 1.2 second, as this is the average burst interval? Or would it be better to split the matrix when there is a too large gap (say 5 seconds), and let YAPS run over the different matrices seperately (and still for this matrices fill the smaller gaps)...?

Then another question: why is it that you need the grid centred close to (0,0)?

Thanks a lot!

**Comment by JennaVergeynst** [comment]
Btw, with pingtype on random burst interval and cleaned TOA matrix, I'm getting a nice track! :-)

**Comment by JennaVergeynst** [comment]
Hi Henrik,

It's a uniform distribution I guess. Actually Vemco configures the tag so that it emits randomly between 1.1 and 1.3. They do so to avoid that to fish would ping constantly at the same moment and would cause constant collisions...

The other pings come from the same tag indeed. Well, the 1.1-1.3 are HR-transmissions (High Residence, their new technique), those have a short pulse of about 6 ms. The 50-70s are PPM tranmissions (Pulse Position Modulation, their old technique which takes some seconds to transmit). I think they use both because older receivers only detect PPM, for presence/absence detection further in the network.

So in which case would you use rbi than, only if the interval is of a certain size?

Really 30 to 60 minutes? So the algorithm should be able to cope with 30 minutes silence and than create a new track? Then the output would consist of different seperated tracks?

**Comment by JennaVergeynst** [comment]
Hi,

Just to mention that I still need to use the rbi version for these data: when I use sbi I get a track that is hugely different, and with mean error of 21 m (versus 0.7 m for rbi)...

![46902_rbi_vs_sbi](https://user-images.githubusercontent.com/18457551/52066093-247d3780-2578-11e9-99c0-c3103d66d17b.png)

Btw, I have some code to prepare this cleaned TOA-matrix where the gaps are filled and double rows for one ping omitted (as good as possible), departing from synchronised detection data. It is based on the data format as delivered by Vemco, and it is also in python... But it might be a help to start from for other people who want to use yaps, so maybe it's interesting to share it on your github page? Let me know if you're interested, then I'll make a branch.

**Comment by baktoft** [comment]
Thanks for the feed back and info re sbi vs rbi for these data. I am a bit surprised by the crappy track from sbi, but so be it. Maybe changing the inits would help... Anyways, guess the rbi solution looks ok. Do you have any gps'ed test tracks to test it against?
