### ISSUE TITLE
Include soundspeed data

### ISSUE THREAD

**Issue by JennaVergeynst** [baktoft/yaps#3]
Hi again @baktoft ,

Is there a way to include soundspeed data when using the package?

Thanks,
Jenna

**Comment by baktoft** [comment]
Hi @JennaVergeynst 
At the moment, sound speed is estimated by the model. However, there are situations where it would be beneficial to use recorded water temperature and sound speeds estimated from that as input to the model instead. I can include the option for doing that - when do you need it?
Cheers, \hb

**Comment by JennaVergeynst** [comment]
Well ... My collaborator is waiting for my tracks so it would be nice to have that option... I'm not sure if it will bring a great improvement of course, but it can be good to test, since we have those data available. So whenever you have time...

**Comment by JennaVergeynst** [comment]
Hi @baktoft,

A question related to the above...
In the function "getInp", n_ss is specified, I suppose this is the number of soundspeed estimations? Should this not always be equal to the number of pings, or the lenght of the track, i.e. one soundspeed estimation for each transmission?

Btw, do you have some documentation on the functions getInp and runTmb?

Jenna

**Comment by JennaVergeynst** [comment]
Ah ok!

I installed it as:

```
install.packages('devtools')
devtools::install_github("baktoft/yaps")
```

I did not get any errors. But indeed, R-help says "No documentation for ... in specified package and libraries."

**Comment by baktoft** [comment]
Seems like I managed to get man pages into .gitignore, so they were not uploaded. Should work now, so please try again.
Cheers,
\hb

**Comment by JennaVergeynst** [comment]
Yes, thanks, that works now!

**Comment by baktoft** [comment]
Hi Jenna,
I tried to implement the option to use SS from measured water temperature - branch use_ss-data. Could you take it for a spin?
Install using `devtools::install_github("baktoft/yaps", ref="use_ss-data")` and see the [README.md](https://github.com/baktoft/yaps/blob/use_ss-data/README.md) from that branch for example using this option.

Cheers, \hb

**Comment by JennaVergeynst** [comment]
Thanks Henrik,
I tested this branch and it works smoothly.
However for these data the difference with modelled soundspeed is very small. The modelled errors are even slightly larger when including measured soundspeed... I will test it also for the PPM data later on!

**Comment by baktoft** [comment]
Thanks for testing 👍 
In cases with decent number of hydros detecting the pings, SS can be estimated very well. Obviously, at some threshold it will be better to use measured SS, so good to have the option ready.
As for larger errors when using measured... I think the SS estimation capture a bit of variation that otherwise end up in the residuals/error estimates. Perhaps left-overs from non-perfect hydro synchronization...

**Comment by baktoft** [comment]
Option to use SS-data from measure water temperature added. Thanks to @JennaVergeynst for suggestion, feedback and test.
